#!/bin/sh
set -eu

APP_NAME="${APP_NAME:-$(basename "$PWD")}"
COMPOSE_FILE="${COMPOSE_FILE:-compose.yml}"
SERVICE_NAME="${SERVICE_NAME:-$APP_NAME}"
CONTAINER_NAME="${CONTAINER_NAME:-$SERVICE_NAME}"

COMPOSE_FILE="$COMPOSE_FILE" SERVICE_NAME="$SERVICE_NAME" CONTAINER_NAME="$CONTAINER_NAME" ./stop.sh
COMPOSE_FILE="$COMPOSE_FILE" SERVICE_NAME="$SERVICE_NAME" CONTAINER_NAME="$CONTAINER_NAME" ./start.sh

