"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-14

Authored directly (not autogenerated) so the two seed Plan rows can be
inserted via op.bulk_insert in the same migration as the schema that needs
them.
"""

import uuid
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FREE_PLAN_ID = uuid.UUID("00000000-0000-0000-0000-000000000001")
PRO_PLAN_ID = uuid.UUID("00000000-0000-0000-0000-000000000002")


def _timestamps():
    return [
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
    ]


def _profile_columns():
    """Shared columns for the 5 profile/preset tables (mirrors ProfileBase)."""
    return [
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("is_default", sa.Boolean, nullable=False, server_default=sa.false()),
        *_timestamps(),
    ]


def upgrade() -> None:
    # --- plans ---------------------------------------------------------------
    op.create_table(
        "plans",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("key", sa.String(50), nullable=False, unique=True),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("max_shops", sa.Integer, nullable=True),
        sa.Column("max_toolboxes", sa.Integer, nullable=True),
        sa.Column("max_drawers", sa.Integer, nullable=True),
        sa.Column("max_users", sa.Integer, nullable=True),
        *_timestamps(),
    )

    # --- organizations ---------------------------------------------------------------
    op.create_table(
        "organizations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("slug", sa.String(120), nullable=False, unique=True),
        sa.Column("plan_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("plans.id"), nullable=False),
        *_timestamps(),
    )

    # --- users ---------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(320), nullable=False, unique=True),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("display_name", sa.String(200), nullable=True),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        *_timestamps(),
    )

    # --- memberships ---------------------------------------------------------------
    op.create_table(
        "memberships",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("role", sa.String(20), nullable=False),
        *_timestamps(),
        sa.UniqueConstraint("organization_id", "user_id", name="uq_membership_org_user"),
        sa.CheckConstraint("role IN ('owner', 'admin', 'member')", name="ck_membership_role"),
    )
    op.create_index("ix_memberships_organization_id", "memberships", ["organization_id"])
    op.create_index("ix_memberships_user_id", "memberships", ["user_id"])

    # --- shops ---------------------------------------------------------------
    op.create_table(
        "shops",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("slug", sa.String(120), nullable=False),
        sa.Column("location", sa.String(300), nullable=True),
        *_timestamps(),
        sa.UniqueConstraint("organization_id", "slug", name="uq_shop_org_slug"),
    )
    op.create_index("ix_shops_organization_id", "shops", ["organization_id"])

    # --- toolboxes ---------------------------------------------------------------
    op.create_table(
        "toolboxes",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "shop_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("shops.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("kind", sa.String(100), nullable=True),
        sa.Column("notes", sa.String(2000), nullable=True),
        *_timestamps(),
    )
    op.create_index("ix_toolboxes_shop_id", "toolboxes", ["shop_id"])

    # --- drawer_profiles (profile preset) ---------------------------------------------------------------
    op.create_table(
        "drawer_profiles",
        *_profile_columns(),
        sa.Column("inside_width_mm", sa.Numeric(8, 3), nullable=False),
        sa.Column("inside_depth_mm", sa.Numeric(8, 3), nullable=False),
        sa.Column("inside_height_mm", sa.Numeric(8, 3), nullable=False),
        sa.Column("grid_unit_mm", sa.Numeric(6, 3), nullable=False, server_default="42"),
        sa.UniqueConstraint("organization_id", "name", name="uq_drawer_profile_org_name"),
    )
    op.create_index("ix_drawer_profiles_organization_id", "drawer_profiles", ["organization_id"])

    # --- printer_profiles ---------------------------------------------------------------
    op.create_table(
        "printer_profiles",
        *_profile_columns(),
        sa.Column("manufacturer", sa.String(200), nullable=True),
        sa.Column("model", sa.String(200), nullable=True),
        sa.Column("build_width_mm", sa.Numeric(8, 3), nullable=False),
        sa.Column("build_depth_mm", sa.Numeric(8, 3), nullable=False),
        sa.Column("build_height_mm", sa.Numeric(8, 3), nullable=False),
        sa.Column("nozzle_diameter_mm", sa.Numeric(6, 3), nullable=False, server_default="0.4"),
        sa.Column("usable_margin_mm", sa.Numeric(6, 3), nullable=False, server_default="2.0"),
        sa.UniqueConstraint("organization_id", "name", name="uq_printer_profile_org_name"),
    )
    op.create_index("ix_printer_profiles_organization_id", "printer_profiles", ["organization_id"])

    # --- magnet_profiles ---------------------------------------------------------------
    op.create_table(
        "magnet_profiles",
        *_profile_columns(),
        sa.Column("diameter_mm", sa.Numeric(6, 3), nullable=False),
        sa.Column("thickness_mm", sa.Numeric(6, 3), nullable=False),
        sa.Column("diameter_clearance_mm", sa.Numeric(6, 3), nullable=False, server_default="0.2"),
        sa.Column("depth_clearance_mm", sa.Numeric(6, 3), nullable=False, server_default="0.2"),
        sa.Column("fit_type", sa.String(30), nullable=False, server_default="glue"),
        sa.UniqueConstraint("organization_id", "name", name="uq_magnet_profile_org_name"),
    )
    op.create_index("ix_magnet_profiles_organization_id", "magnet_profiles", ["organization_id"])

    # --- material_profiles ---------------------------------------------------------------
    op.create_table(
        "material_profiles",
        *_profile_columns(),
        sa.Column("material_type", sa.String(50), nullable=False),
        sa.Column("xy_compensation_mm", sa.Numeric(6, 3), nullable=False, server_default="0"),
        sa.Column("notes", sa.String(1000), nullable=True),
        sa.UniqueConstraint("organization_id", "name", name="uq_material_profile_org_name"),
    )
    op.create_index("ix_material_profiles_organization_id", "material_profiles", ["organization_id"])

    # --- label_style_profiles ---------------------------------------------------------------
    op.create_table(
        "label_style_profiles",
        *_profile_columns(),
        sa.Column("text_height_mm", sa.Numeric(6, 3), nullable=False, server_default="15.843"),
        sa.Column("body_depth_mm", sa.Numeric(6, 3), nullable=False, server_default="4.55"),
        sa.Column("outline_offset_mm", sa.Numeric(6, 3), nullable=False, server_default="1.25"),
        sa.Column("font_family", sa.String(200), nullable=False, server_default="DejaVu Sans"),
        sa.Column("font_weight", sa.String(30), nullable=False, server_default="bold"),
        sa.Column("font_style", sa.String(30), nullable=False, server_default="italic"),
        sa.Column("horizontal_scale", sa.Numeric(6, 3), nullable=False, server_default="1.0"),
        sa.Column("minimum_width_mm", sa.Numeric(8, 3), nullable=False, server_default="24.0"),
        sa.Column("fixed_width_mm", sa.Numeric(8, 3), nullable=True),
        sa.Column("magnet_count", sa.Integer, nullable=False, server_default="2"),
        sa.Column("magnet_edge_offset_mm", sa.Numeric(6, 3), nullable=False, server_default="8.0"),
        sa.Column("magnet_minimum_bridge_mm", sa.Numeric(6, 3), nullable=False, server_default="0.6"),
        sa.Column("magnet_support_extra_mm", sa.Numeric(6, 3), nullable=False, server_default="0.0"),
        sa.Column(
            "default_magnet_profile_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("magnet_profiles.id"),
            nullable=True,
        ),
        sa.UniqueConstraint("organization_id", "name", name="uq_label_style_profile_org_name"),
    )
    op.create_index("ix_label_style_profiles_organization_id", "label_style_profiles", ["organization_id"])

    # --- drawers (physical instance) ---------------------------------------------------------------
    op.create_table(
        "drawers",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "toolbox_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("toolboxes.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "drawer_profile_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("drawer_profiles.id"), nullable=False
        ),
        sa.Column("name", sa.String(200), nullable=True),
        sa.Column("position_label", sa.String(100), nullable=True),
        sa.Column("notes", sa.String(2000), nullable=True),
        *_timestamps(),
    )
    op.create_index("ix_drawers_toolbox_id", "drawers", ["toolbox_id"])
    op.create_index("ix_drawers_drawer_profile_id", "drawers", ["drawer_profile_id"])

    # --- tools ---------------------------------------------------------------
    op.create_table(
        "tools",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("category", sa.String(100), nullable=True),
        sa.Column("manufacturer", sa.String(200), nullable=True),
        sa.Column("sku", sa.String(100), nullable=True),
        sa.Column("notes", sa.String(2000), nullable=True),
        sa.Column(
            "drawer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("drawers.id", ondelete="SET NULL"), nullable=True
        ),
        sa.Column("quantity", sa.Integer, nullable=False, server_default="1"),
        *_timestamps(),
    )
    op.create_index("ix_tools_organization_id", "tools", ["organization_id"])
    op.create_index("ix_tools_drawer_id", "tools", ["drawer_id"])

    # --- designs (M2 router, schema only for now) ---------------------------------------------------------------
    op.create_table(
        "designs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "shop_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("shops.id", ondelete="SET NULL"), nullable=True
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("text", sa.String(500), nullable=False),
        sa.Column(
            "label_style_profile_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("label_style_profiles.id"),
            nullable=True,
        ),
        sa.Column(
            "magnet_profile_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("magnet_profiles.id"), nullable=True
        ),
        sa.Column("parameters_json", postgresql.JSONB, nullable=False),
        sa.Column("engine_version", sa.String(50), nullable=False),
        sa.Column("content_hash", sa.String(64), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        sa.Column("outline_stl_path", sa.String(500), nullable=True),
        sa.Column("text_stl_path", sa.String(500), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
        sa.CheckConstraint("status IN ('draft', 'queued', 'generated', 'failed')", name="ck_design_status"),
    )
    op.create_index("ix_designs_organization_id", "designs", ["organization_id"])
    op.create_index("ix_designs_shop_id", "designs", ["shop_id"])

    # --- Gridfinity stub tables (schema only, zero logic) ---------------------------------------------------------------
    op.create_table(
        "insert_designs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("source", sa.String(20), nullable=False),
        sa.Column("source_reference", sa.String(500), nullable=True),
        sa.Column("stl_path", sa.String(500), nullable=True),
        sa.Column("bounds_json", postgresql.JSONB, nullable=True),
        *_timestamps(),
        sa.CheckConstraint("source IN ('upload', 'tooltrace', 'generated')", name="ck_insert_design_source"),
    )
    op.create_index("ix_insert_designs_organization_id", "insert_designs", ["organization_id"])

    op.create_table(
        "drawer_layouts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "drawer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("drawers.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        sa.Column("layout_json", postgresql.JSONB, nullable=True),
        sa.Column(
            "printer_profile_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("printer_profiles.id"),
            nullable=True,
        ),
        *_timestamps(),
        sa.CheckConstraint("status IN ('draft', 'computed', 'exported')", name="ck_drawer_layout_status"),
    )
    op.create_index("ix_drawer_layouts_drawer_id", "drawer_layouts", ["drawer_id"])

    op.create_table(
        "insert_placements",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "drawer_layout_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("drawer_layouts.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "insert_design_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("insert_designs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("x_mm", sa.Numeric(8, 3), nullable=False, server_default="0"),
        sa.Column("y_mm", sa.Numeric(8, 3), nullable=False, server_default="0"),
        sa.Column("rotation_deg", sa.Numeric(6, 2), nullable=False, server_default="0"),
        *_timestamps(),
    )
    op.create_index("ix_insert_placements_drawer_layout_id", "insert_placements", ["drawer_layout_id"])
    op.create_index("ix_insert_placements_insert_design_id", "insert_placements", ["insert_design_id"])

    # --- seed data ---------------------------------------------------------------
    plans_table = sa.table(
        "plans",
        sa.column("id", postgresql.UUID(as_uuid=True)),
        sa.column("key", sa.String),
        sa.column("name", sa.String),
        sa.column("max_shops", sa.Integer),
        sa.column("max_toolboxes", sa.Integer),
        sa.column("max_drawers", sa.Integer),
        sa.column("max_users", sa.Integer),
    )
    op.bulk_insert(
        plans_table,
        [
            {
                "id": FREE_PLAN_ID,
                "key": "free",
                "name": "Free",
                "max_shops": 1,
                "max_toolboxes": 1,
                "max_drawers": 5,
                "max_users": 1,
            },
            {
                "id": PRO_PLAN_ID,
                "key": "pro",
                "name": "Pro",
                "max_shops": None,
                "max_toolboxes": None,
                "max_drawers": None,
                "max_users": None,
            },
        ],
    )


def downgrade() -> None:
    op.drop_table("insert_placements")
    op.drop_table("drawer_layouts")
    op.drop_table("insert_designs")
    op.drop_table("designs")
    op.drop_table("tools")
    op.drop_table("drawers")
    op.drop_table("label_style_profiles")
    op.drop_table("material_profiles")
    op.drop_table("magnet_profiles")
    op.drop_table("printer_profiles")
    op.drop_table("drawer_profiles")
    op.drop_table("toolboxes")
    op.drop_table("shops")
    op.drop_table("memberships")
    op.drop_table("users")
    op.drop_table("organizations")
    op.drop_table("plans")
