"""roadmap items

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-15

Authored directly (not autogenerated) so the initial roadmap history can be
seeded via op.bulk_insert in the same migration -- mirrors how 0001 seeded
the Plan rows. `roadmap_items` is deliberately NOT organization-scoped: it's
a product roadmap (WorkshopOS's own development progress), not per-tenant
data, so every authenticated user sees the same shared list.
"""

import uuid
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "roadmap_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="planned"),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('planned', 'in_progress', 'done')", name="ck_roadmap_item_status"),
    )

    roadmap_table = sa.table(
        "roadmap_items",
        sa.column("id", postgresql.UUID(as_uuid=True)),
        sa.column("title", sa.String),
        sa.column("description", sa.Text),
        sa.column("status", sa.String),
        sa.column("position", sa.Integer),
    )
    op.bulk_insert(
        roadmap_table,
        [
            {
                "id": uuid.uuid4(),
                "title": "Ground-zero rebuild scaffold",
                "description": "Multi-tenant schema (Org/Plan/User/Membership), auth, Shop/Toolbox/Drawer/Tool CRUD, all 5 profile types, Docker Compose deployment behind Caddy/Cloudflared.",
                "status": "done",
                "position": 0,
            },
            {
                "id": uuid.uuid4(),
                "title": "Label Designer",
                "description": "Parametric magnet-backed drawer/toolbox label generation (ported geometry engine), 3D preview, STL download.",
                "status": "done",
                "position": 1,
            },
            {
                "id": uuid.uuid4(),
                "title": "Gridfinity bin generator",
                "description": "Parametric baseplate-compatible storage bins -- grid dimensions, compartments, stacking lip, magnet holes -- built from scratch against researched Gridfinity spec dimensions.",
                "status": "done",
                "position": 2,
            },
            {
                "id": uuid.uuid4(),
                "title": "STL import",
                "description": "Upload externally-sourced STL files (community downloads, tooltrace.ai exports) as inserts, unified with generated bins in one Inserts list.",
                "status": "done",
                "position": 3,
            },
            {
                "id": uuid.uuid4(),
                "title": "Tool ↔ insert linkage",
                "description": "Associate a Tool with the InsertDesign (STL) that holds it, so a drawer's tool list can drive automatic layout generation.",
                "status": "planned",
                "position": 4,
            },
            {
                "id": uuid.uuid4(),
                "title": "Drawer auto-layout / packing algorithm",
                "description": "Select a drawer and its tools, generate the most space-efficient arrangement of their inserts -- printer-agnostic, real mm coordinates, no print-bed splitting yet.",
                "status": "planned",
                "position": 5,
            },
            {
                "id": uuid.uuid4(),
                "title": "Bin merging",
                "description": "Merge adjacent generated bins into single printable bodies to reduce wasted material and print time.",
                "status": "planned",
                "position": 6,
            },
            {
                "id": uuid.uuid4(),
                "title": "Print-bed panelization at export",
                "description": "Pick a printer at export time and split a finished drawer layout across however many bed-sized plates it takes -- separate from layout generation since different printers have different bed sizes.",
                "status": "planned",
                "position": 7,
            },
            {
                "id": uuid.uuid4(),
                "title": "Billing / plan enforcement",
                "description": "Stripe or similar, real license-key validation for self-hosted Pro. Plan/plan_id and count-based limits already exist in the schema; no payment infrastructure yet.",
                "status": "planned",
                "position": 8,
            },
            {
                "id": uuid.uuid4(),
                "title": "Member invites",
                "description": "Invite additional users into an organization with a real role (owner/admin/member is already modeled on Membership, but nothing enforces it yet and only the registering user gets added today).",
                "status": "planned",
                "position": 9,
            },
        ],
    )


def downgrade() -> None:
    op.drop_table("roadmap_items")
