import * as React from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import axios from "axios";
import { Download, Loader2, Trash2 } from "lucide-react";
import { useForm } from "react-hook-form";
import { Link, useNavigate, useParams } from "react-router-dom";
import { z } from "zod";
import type { InsertDesign, Plate, Tool } from "@/lib/types";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  drawerLayoutsApi,
  drawerProfilesApi,
  drawersApi,
  fetchPlateFile,
  insertDesignsApi,
  printerProfilesApi,
  toolsApi,
  triggerBlobDownload,
} from "@/lib/api";
import {
  colorForIndex,
  computeScale,
  getInsertBounds,
  placementRectPx,
} from "@/lib/drawerLayoutGeometry";

// Reasonable pixel budget for the SVG panel -- the larger of the drawer's
// two interior dimensions maps to this many px, the other scales
// proportionally (see `computeScale`).
const LAYOUT_PIXEL_BUDGET = 560;

const drawerSchema = z.object({
  drawer_profile_id: z.string().min(1, "Required"),
  name: z.string().optional(),
  position_label: z.string().optional(),
  notes: z.string().optional(),
  row: z.string().optional(),
});
type DrawerFormValues = z.infer<typeof drawerSchema>;

export function DrawerDetail() {
  const { shopId, toolboxId, drawerId } = useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const drawerQuery = useQuery({
    queryKey: ["drawers", drawerId],
    queryFn: () => drawersApi.get(shopId as string, toolboxId as string, drawerId as string),
    enabled: !!shopId && !!toolboxId && !!drawerId,
  });
  const drawerProfilesQuery = useQuery({
    queryKey: ["profiles", "drawer-profiles"],
    queryFn: () => drawerProfilesApi.list(),
  });
  // The tools list is org-wide (no server-side drawer filter) -- filter
  // client-side, same pattern ToolsPage already uses for its own filters.
  const allToolsQuery = useQuery({ queryKey: ["tools"], queryFn: () => toolsApi.list() });
  const toolsInDrawer = React.useMemo(
    () => (allToolsQuery.data ?? []).filter((t: Tool) => t.drawer_id === drawerId),
    [allToolsQuery.data, drawerId],
  );
  const toolNameById = React.useMemo(() => {
    const map = new Map<string, string>();
    (allToolsQuery.data ?? []).forEach((t: Tool) => map.set(t.id, t.name));
    return map;
  }, [allToolsQuery.data]);

  // Layout section (Milestone 3 Phase 3): resolves each placement's
  // `insert_design_id` -> `InsertDesign` for its name + `bounds_json`
  // footprint, same lookup-map pattern as `drawerLabelById`/
  // `insertLabelById` in ToolsPage.tsx.
  const insertDesignsQuery = useQuery({
    queryKey: ["insert-designs"],
    queryFn: () => insertDesignsApi.list(),
  });
  const insertDesignById = React.useMemo(() => {
    const map = new Map<string, InsertDesign>();
    (insertDesignsQuery.data ?? []).forEach((d) => map.set(d.id, d));
    return map;
  }, [insertDesignsQuery.data]);

  const layoutsQuery = useQuery({
    queryKey: ["drawer-layouts", drawerId],
    queryFn: () => drawerLayoutsApi.list(shopId as string, toolboxId as string, drawerId as string),
    enabled: !!shopId && !!toolboxId && !!drawerId,
    // Milestone 3 Phase 5: poll while any plate on the latest layout is
    // still being generated by the background worker -- `plates` lives
    // inside the layout row already fetched here, so this reuses the
    // existing query rather than adding a separate one. Same
    // interval/callback-form shape as `InsertDetail.tsx`'s
    // `refetchInterval: (query) => (query.state.data?.status === "queued" ? 1500 : false)`.
    refetchInterval: (query) =>
      query.state.data?.[0]?.layout_json.plates?.some((p) => p.status === "queued")
        ? 1500
        : false,
  });
  // Newest first per the API contract -- the most recent generation is what
  // the panel below renders; older entries remain fetchable via `list()`
  // for future history UI, not built here (out of this phase's scope).
  const latestLayout = layoutsQuery.data?.[0];

  const generateLayoutMutation = useMutation({
    mutationFn: () =>
      drawerLayoutsApi.generate(shopId as string, toolboxId as string, drawerId as string),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["drawer-layouts", drawerId] });
    },
  });

  // Milestone 3 Phase 4: merging derives a NEW layout from the current
  // latest one (immutable-snapshot pattern, same as generate) -- the old
  // layout and its placements/InsertDesigns are untouched, this just makes
  // the merged result the new "latest" via the same invalidate/refetch.
  const mergeLayoutMutation = useMutation({
    mutationFn: () =>
      drawerLayoutsApi.merge(
        shopId as string,
        toolboxId as string,
        drawerId as string,
        (latestLayout as NonNullable<typeof latestLayout>).id,
      ),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["drawer-layouts", drawerId] });
    },
  });

  // Milestone 3 Phase 5 (print-bed panelization at export): printer profile
  // picker feeding `exportLayoutMutation`, same `<Select>` component already
  // used for the drawer-profile picker in this file's form below.
  const printerProfilesQuery = useQuery({
    queryKey: ["profiles", "printer-profiles"],
    queryFn: () => printerProfilesApi.list(),
  });
  const [selectedPrinterId, setSelectedPrinterId] = React.useState<string>("");

  const exportLayoutMutation = useMutation({
    mutationFn: () =>
      drawerLayoutsApi.export(
        shopId as string,
        toolboxId as string,
        drawerId as string,
        (latestLayout as NonNullable<typeof latestLayout>).id,
        selectedPrinterId,
      ),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["drawer-layouts", drawerId] });
    },
  });

  const selectedDrawerProfile = React.useMemo(
    () =>
      (drawerProfilesQuery.data ?? []).find(
        (p) => p.id === drawerQuery.data?.drawer_profile_id,
      ),
    [drawerProfilesQuery.data, drawerQuery.data],
  );
  const layoutScale = selectedDrawerProfile
    ? computeScale(
        selectedDrawerProfile.inside_width_mm,
        selectedDrawerProfile.inside_depth_mm,
        LAYOUT_PIXEL_BUDGET,
      )
    : 0;
  const viewportWidthPx = selectedDrawerProfile
    ? selectedDrawerProfile.inside_width_mm * layoutScale
    : 0;
  const viewportHeightPx = selectedDrawerProfile
    ? selectedDrawerProfile.inside_depth_mm * layoutScale
    : 0;

  const form = useForm<DrawerFormValues>({ resolver: zodResolver(drawerSchema) });
  React.useEffect(() => {
    if (drawerQuery.data) {
      form.reset({
        drawer_profile_id: drawerQuery.data.drawer_profile_id,
        name: drawerQuery.data.name ?? "",
        position_label: drawerQuery.data.position_label ?? "",
        notes: drawerQuery.data.notes ?? "",
        row: drawerQuery.data.row?.toString() ?? "",
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [drawerQuery.data]);

  const updateMutation = useMutation({
    mutationFn: (values: DrawerFormValues) =>
      drawersApi.update(shopId as string, toolboxId as string, drawerId as string, {
        ...values,
        row: values.row ? Number(values.row) : null,
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["drawers"] });
    },
  });

  const deleteMutation = useMutation({
    mutationFn: () => drawersApi.remove(shopId as string, toolboxId as string, drawerId as string),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["drawers"] });
      navigate(`/shops/${shopId}/toolboxes/${toolboxId}`);
    },
  });

  if (drawerQuery.isLoading) {
    return <p className="p-4 text-sm text-muted-foreground">Loading drawer…</p>;
  }
  if (drawerQuery.isError || !drawerQuery.data) {
    return <p className="p-4 text-sm text-destructive">Drawer not found.</p>;
  }

  const selectedProfileId = form.watch("drawer_profile_id");
  // See `DrawerLayoutJson.plates`'s doc comment -- the key is genuinely
  // absent (not `[]`) on a pre-export layout, confirmed against the live
  // backend, so this normalizes once here rather than repeating `?? []` at
  // every call site below.
  const latestLayoutPlates = latestLayout?.layout_json.plates ?? [];

  return (
    <div className="flex flex-col gap-6 p-4">
      <section>
        <div className="mb-3 flex items-center justify-between">
          <h1 className="text-base font-semibold">
            {drawerQuery.data.name || drawerQuery.data.position_label || "Drawer"}
          </h1>
          <Button
            size="sm"
            variant="destructive"
            onClick={() => {
              if (confirm("Delete this drawer?")) deleteMutation.mutate();
            }}
          >
            <Trash2 />
            Delete drawer
          </Button>
        </div>
        <form
          onSubmit={form.handleSubmit((v) => updateMutation.mutate(v))}
          className="grid max-w-lg grid-cols-2 gap-3"
        >
          <div className="col-span-2 flex flex-col gap-1">
            <Label htmlFor="dr-profile">Drawer profile</Label>
            <Select
              value={selectedProfileId}
              onValueChange={(v) => form.setValue("drawer_profile_id", v)}
            >
              <SelectTrigger id="dr-profile">
                <SelectValue placeholder="Select a profile…" />
              </SelectTrigger>
              <SelectContent>
                {(drawerProfilesQuery.data ?? []).map((p) => (
                  <SelectItem key={p.id} value={p.id}>
                    {p.name} ({p.inside_width_mm}×{p.inside_depth_mm}×
                    {p.inside_height_mm}mm)
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="flex flex-col gap-1">
            <Label htmlFor="name">Name</Label>
            <Input id="name" {...form.register("name")} />
          </div>
          <div className="flex flex-col gap-1">
            <Label htmlFor="position_label">Position label</Label>
            <Input id="position_label" {...form.register("position_label")} />
          </div>
          <div className="flex flex-col gap-1">
            <Label htmlFor="row">Row</Label>
            <Input id="row" type="number" placeholder="1" {...form.register("row")} />
          </div>
          <div className="col-span-2 flex flex-col gap-1">
            <Label htmlFor="notes">Notes</Label>
            <Input id="notes" {...form.register("notes")} />
          </div>
          <div className="col-span-2">
            <Button type="submit" size="sm" disabled={updateMutation.isPending}>
              {updateMutation.isPending ? "Saving…" : "Save changes"}
            </Button>
          </div>
        </form>
      </section>

      <section>
        <div className="mb-3 flex items-center justify-between">
          <h2 className="text-sm font-semibold">Tools in this drawer</h2>
          <Link to="/tools" className="text-xs text-primary hover:underline">
            Manage in Tools →
          </Link>
        </div>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Name</TableHead>
              <TableHead>Category</TableHead>
              <TableHead>Qty</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {toolsInDrawer.map((tool) => (
              <TableRow key={tool.id}>
                <TableCell className="font-medium">{tool.name}</TableCell>
                <TableCell className="text-muted-foreground">
                  {tool.category || "—"}
                </TableCell>
                <TableCell className="font-mono">{tool.quantity}</TableCell>
              </TableRow>
            ))}
            {allToolsQuery.isSuccess && toolsInDrawer.length === 0 && (
              <TableRow>
                <TableCell colSpan={3} className="py-6 text-center text-muted-foreground">
                  No tools assigned to this drawer yet.
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </section>

      <section>
        <div className="mb-3 flex items-center justify-between">
          <h2 className="text-sm font-semibold">Layout</h2>
          <div className="flex items-center gap-3">
            {latestLayout && (
              <span className="text-xs text-muted-foreground">
                Utilization:{" "}
                <span className="font-mono text-foreground">
                  {latestLayout.layout_json.utilization_pct.toFixed(1)}%
                </span>
              </span>
            )}
            <Button
              size="sm"
              variant="outline"
              onClick={() => mergeLayoutMutation.mutate()}
              disabled={!latestLayout || mergeLayoutMutation.isPending}
            >
              {mergeLayoutMutation.isPending ? "Merging…" : "Merge adjacent bins"}
            </Button>
            <Button
              size="sm"
              onClick={() => generateLayoutMutation.mutate()}
              disabled={generateLayoutMutation.isPending}
            >
              {generateLayoutMutation.isPending ? "Generating…" : "Generate layout"}
            </Button>
          </div>
        </div>

        {generateLayoutMutation.isError && (
          <p className="mb-3 text-xs text-destructive">
            {axios.isAxiosError(generateLayoutMutation.error) &&
            generateLayoutMutation.error.response?.status === 422
              ? "No tools in this drawer have a linked insert -- nothing to pack. Link an insert to at least one tool first."
              : "Failed to generate layout. Please try again."}
          </p>
        )}

        {mergeLayoutMutation.isError && (
          <p className="mb-3 text-xs text-destructive">Failed to merge bins. Please try again.</p>
        )}

        {/* Milestone 3 Phase 5: pick a printer and export the current
            layout's placed bins onto N printer-bed-sized plates. Separate
            control row from Generate/Merge above since it depends on both a
            layout existing AND a printer being selected. */}
        <div className="mb-3 flex items-center gap-3">
          <div className="flex w-56 flex-col gap-1">
            <Label htmlFor="printer-profile" className="text-xs">
              Printer
            </Label>
            <Select value={selectedPrinterId} onValueChange={setSelectedPrinterId}>
              <SelectTrigger id="printer-profile" className="h-8">
                <SelectValue placeholder="Select a printer…" />
              </SelectTrigger>
              <SelectContent>
                {(printerProfilesQuery.data ?? []).map((p) => (
                  <SelectItem key={p.id} value={p.id}>
                    {p.name} ({p.build_width_mm}×{p.build_depth_mm}mm)
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <Button
            size="sm"
            variant="outline"
            onClick={() => exportLayoutMutation.mutate()}
            disabled={!latestLayout || !selectedPrinterId || exportLayoutMutation.isPending}
          >
            {exportLayoutMutation.isPending ? "Exporting…" : "Export for printer"}
          </Button>
        </div>

        {exportLayoutMutation.isError && (
          <p className="mb-3 text-xs text-destructive">
            {axios.isAxiosError(exportLayoutMutation.error) &&
            exportLayoutMutation.error.response?.status === 422
              ? "This layout has no placed bins to export yet."
              : "Failed to export layout. Please try again."}
          </p>
        )}

        {/* Reads the persisted `merges` field off whichever layout is
            currently displayed, rather than the merge mutation's own
            isSuccess/data -- that would go stale the moment the user clicks
            "Generate layout" again afterward, showing an outdated merge
            confirmation next to an unrelated fresh layout. This way the
            message always reflects the layout actually on screen: empty
            because it came from a plain generate, or because a merge ran
            and found nothing, both render the same (accurate) empty state. */}
        {latestLayout && latestLayout.layout_json.merges.length > 0 && (
          <p className="mb-3 text-xs text-muted-foreground">
            This layout merged{" "}
            <span className="font-mono text-foreground">
              {latestLayout.layout_json.merges.reduce((sum, m) => sum + m.source_placement_count, 0)}
            </span>{" "}
            bins into{" "}
            <span className="font-mono text-foreground">{latestLayout.layout_json.merges.length}</span>.
          </p>
        )}

        {layoutsQuery.isLoading && (
          <p className="text-xs text-muted-foreground">Loading layouts…</p>
        )}

        {!layoutsQuery.isLoading && !latestLayout && !generateLayoutMutation.isError && (
          <p className="text-xs text-muted-foreground">
            No layout generated yet. Link tools to inserts above, then generate one.
          </p>
        )}

        {latestLayout && (
          <div className="flex flex-col gap-4 lg:flex-row">
            <div className="overflow-auto rounded-md border border-border bg-muted/20 p-2">
              {selectedDrawerProfile ? (
                <svg
                  width={viewportWidthPx}
                  height={viewportHeightPx}
                  viewBox={`0 0 ${viewportWidthPx} ${viewportHeightPx}`}
                  className="block"
                  role="img"
                  aria-label="Drawer layout"
                >
                  <rect
                    x={0}
                    y={0}
                    width={viewportWidthPx}
                    height={viewportHeightPx}
                    fill="none"
                    stroke="currentColor"
                    className="text-border"
                    strokeWidth={1}
                  />
                  {latestLayout.placements.map((placement, i) => {
                    const design = insertDesignById.get(placement.insert_design_id);
                    const bounds = getInsertBounds(design?.bounds_json ?? null);
                    if (!bounds) return null;
                    const rect = placementRectPx(
                      placement.x_mm,
                      placement.y_mm,
                      bounds,
                      placement.rotation_deg,
                      layoutScale,
                    );
                    return (
                      <g key={placement.id}>
                        <rect
                          x={rect.x}
                          y={rect.y}
                          width={rect.width}
                          height={rect.height}
                          fill={colorForIndex(i)}
                          stroke="currentColor"
                          className="text-foreground/50"
                          strokeWidth={1}
                        />
                        <text
                          x={rect.x + 4}
                          y={rect.y + 13}
                          fontSize={10}
                          className="fill-foreground"
                        >
                          {design?.name ?? "Unknown insert"}
                        </text>
                      </g>
                    );
                  })}
                </svg>
              ) : (
                <p className="p-2 text-xs text-destructive">
                  Drawer profile not found -- cannot size the layout panel.
                </p>
              )}
            </div>

            {/* Deliberately always visible (not just when non-empty) -- this
                codebase has hit silent-failure UX bugs before (Milestone 2's
                profile forms), so unplaced items get a permanent, hard-to-miss
                spot rather than a conditionally-rendered banner that's easy to
                scroll past. */}
            <div className="min-w-[220px] flex-1">
              <h3 className="mb-1 text-xs font-semibold">
                Unplaced ({latestLayout.layout_json.unplaced.length})
              </h3>
              {latestLayout.layout_json.unplaced.length === 0 ? (
                <p className="rounded-sm border border-border bg-muted/20 px-2 py-1.5 text-xs text-muted-foreground">
                  Everything fit.
                </p>
              ) : (
                <ul className="flex flex-col gap-1">
                  {latestLayout.layout_json.unplaced.map((u, i) => (
                    <li
                      key={`${u.tool_id ?? u.placement_id}-${u.insert_design_id}-${i}`}
                      className="rounded-sm border border-destructive/40 bg-destructive/10 px-2 py-1.5 text-xs"
                    >
                      {/* `tool_id` (generate/merge-produced) and `placement_id`
                          (export/panelize-produced, Milestone 3 Phase 5) are
                          mutually exclusive on the wire -- confirmed live
                          that a panelize entry has no `tool_id` at all, which
                          previously rendered as a blank label here. Fall
                          back to the insert design's own name (already
                          looked up for the SVG panel above) rather than
                          `toolNameById.get(undefined)` silently resolving to
                          nothing. */}
                      <span className="font-medium">
                        {(u.tool_id && toolNameById.get(u.tool_id)) ??
                          insertDesignById.get(u.insert_design_id)?.name ??
                          u.tool_id ??
                          u.insert_design_id}
                      </span>
                      <span className="text-muted-foreground"> — {u.reason}</span>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </div>
        )}

        {/* Milestone 3 Phase 5: per-plate export status. Only appears once
            an export has actually run -- `plates` is not merely empty but
            ABSENT on a freshly-generated or merged (pre-export) layout (the
            live backend response for `generate`/`merge` has no `plates` key
            at all, confirmed against a real running layout during
            verification) -- see `latestLayoutPlates` above for the
            defensive normalization. */}
        {latestLayout && latestLayoutPlates.length > 0 && (
          <div className="mt-4">
            <h3 className="mb-1 text-xs font-semibold">
              Plates ({latestLayoutPlates.length})
            </h3>
            <ul className="flex flex-col gap-1">
              {latestLayoutPlates.map((plate) => (
                <PlateRow
                  key={plate.plate_index}
                  shopId={shopId as string}
                  toolboxId={toolboxId as string}
                  drawerId={drawerId as string}
                  layoutId={latestLayout.id}
                  plate={plate}
                />
              ))}
            </ul>
          </div>
        )}
      </section>
    </div>
  );
}

/**
 * One row in the per-plate export status list. Split into its own
 * component (rather than inlined in the `.map()` above) because the
 * Download button needs its own `useMutation` for the on-demand blob fetch
 * -- calling a hook per loop iteration inside the parent would violate the
 * rules of hooks, same reason `InsertDetail.tsx` keeps its file-fetch query
 * at the top level of a single-item detail page rather than in a list.
 */
function PlateRow({
  shopId,
  toolboxId,
  drawerId,
  layoutId,
  plate,
}: {
  shopId: string;
  toolboxId: string;
  drawerId: string;
  layoutId: string;
  plate: Plate;
}) {
  const downloadMutation = useMutation({
    mutationFn: () =>
      fetchPlateFile(shopId, toolboxId, drawerId, layoutId, plate.plate_index),
    onSuccess: (blob) => {
      triggerBlobDownload(blob, `plate-${plate.plate_index}.stl`);
    },
  });

  return (
    <li className="flex items-center justify-between gap-3 rounded-sm border border-border bg-muted/20 px-2 py-1.5 text-xs">
      <span>
        Plate {plate.plate_index + 1}{" "}
        <span className="text-muted-foreground">
          ({plate.bin_count} bin{plate.bin_count === 1 ? "" : "s"})
        </span>
      </span>
      {plate.status === "queued" && (
        <Badge variant="outline" className="gap-1">
          <Loader2 className="h-3 w-3 animate-spin" />
          Queued
        </Badge>
      )}
      {plate.status === "generated" && (
        <Button
          size="sm"
          variant="outline"
          onClick={() => downloadMutation.mutate()}
          disabled={downloadMutation.isPending}
        >
          <Download />
          {downloadMutation.isPending ? "Downloading…" : "Download"}
        </Button>
      )}
      {plate.status === "failed" && (
        <span className="text-destructive">
          {plate.error_message ?? "Failed to generate this plate."}
        </span>
      )}
    </li>
  );
}
